name: Copper and Coal
favicon: null
layout_spectrum: 0.14253019634634256
typography_spectrum: 0.2768035139888525
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.9044261057861149
  lightness: 0.524562590289861
  saturation: 0.3797523654066026
  rhythmicContrast: 0.23547586100175977
purpose: []
