name: Copper and Coal
favicon: null
layout_spectrum: 0.73305
typography_spectrum: 0.11441
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#101312'
    - '#57493c'
    - '#93898a'
    - '#776250'
    - '#333331'
  brandStrength: 0.75
  lightness: 0.5
  saturation: 0.8125
  rhythmicContrast: 0.25
purpose: []
